### ISSUE TITLE
line 41: syntax error near unexpected token `;;'

### ISSUE THREAD

**Issue by jaggieee** [Alexander88207/RTL8812au-Installer#5]
I think you're closing the  choice too early.

https://github.com/Alexander88207/RTL8812au-Installer/blob/17bdd6508272a5d2938d705f5eb84826e2041131/Installer.sh#L40

Steps to reproduce:
./Installer.sh
Option 2, solus. (happends also on other options)

The script worked fine on Solus when i removed the esac statement on line 40.

**Comment by Alexander88207** [comment]
Yeah I know

**Comment by Alexander88207** [comment]
Hi @jaggieee It's better to send something like that through a pull request the next time :=)

**Comment by jaggieee** [comment]
Hi @Alexander88207,
Didn't know that, i will use a pull request next time.

I really like this script since Solus doesn't use DKMS  to rebuild the driver after a kernel update. Thank you for the effort you put into it 👍

**Comment by Alexander88207** [comment]
Thanks, I'd love to hear that.
